### ISSUE TITLE
Review problem statement

### ISSUE THREAD

**Issue by palmerst** [palmerst/cas741_sp#1]
@smiths My initial revision of the problem statement is ready for review at https://github.com/palmerst/cas741_sp/blob/master/Doc/ProblemStatement/ProblemStatement.pdf

**Comment by smiths** [comment]
Sounds good Steven.  I approve of your problem statement.  I think it is fine that you went with the generalized version.  We can always change the scope back to the Fe(OH)_3 system if we need to.

With respect to your question, the lowest version of Mac OSX that I'm currently using is 10.9.5.

Technically the CAS students aren't stakeholders, if we are "faking" this project, but I'm fine with you listing them.  The line between pretending this is a "real" project and treating it like a course assignment isn't always clear.  😄 

I'm going to send a link to your problem statement to my brother, so that he knows what we are up to.  😄
