### ISSUE TITLE
MG: Speciation Data

### ISSUE THREAD

**Issue by GenevaS** [palmerst/cas741_sp#26]
How is this information being stored? Do you need an additional (specialized) data structure for this?

**Comment by palmerst** [comment]
It isn't actually stored.  The output of the calculation is passed directly to the plotting module which generates a speciation diagram.

Edit:  It is passed around as lists, so it doesn't need a specialized data structure.  This is easier, since the non-linear solver outputs a list of lists and the plotting module operates on lists.
