### ISSUE TITLE
MG: Uses Hierarchy

### ISSUE THREAD

**Issue by GenevaS** [palmerst/cas741_sp#28]
I don't know if this is feasible, but is there some way for you  to decouple either "Equation" from "Species" or "Chemical System" from "Species"? It looks like there are more dependancies here than there needs to be (perhaps symbolic constants could be used in the "Equation" module which could be filled in by the "Chemical System" using information from "Species"?).

**Comment by palmerst** [comment]
I don't think the coupling between these modules is problematic, since they are all highly related to each other.  It is hard to decouple them since reactions involve species, and the chemical system holds information about reactions and species.  I considered other ways of doing this, but this hierarchy produced the cleanest code.  Trying to decouple them results in really awkward code.
