### ISSUE TITLE
SRS Review - Comment #5 - Divide by 0 in T7 and DD1

### ISSUE THREAD

**Issue by slimpotatoes** [palmerst/cas741_sp#7]
- In T7 and DD1, a ratio is present in the equation. While physically, it's impossible to have a zero denominator, you might still be needed to consider it in the document, as an assumption or a data constraint.

**Comment by palmerst** [comment]
DD1 is a set of equations, where the denominator is in terms of symbolic constants for the species concentrations, so there is no risk of DIV0 in DD1. 

The only place it could occur is in the non-linear solver, but since I make it the user's responsibility to ensure correct data and that there is a unique solution, the DIV0 won't be an issue.
